version: "3"
services:
  cms_tst:
    image: dockerhub.icellmobilsoft.hu/modules/cms/cms:3.12.2
    command: ["sh", "-c", "echo 'Node: $$(node -v)' && npm run start || true && npm run start -- --max-old-space-size=2048"]

    # healthcheck:
    #   interval: 1m
    #   retries: 5
    #   start_period: 240s
    #   test:
    #   - CMD
    #   - curl
    #   - -f
    #   - http://localhost:1337
    #   timeout: 10s
    # networks:
    #   - cms
    # ports:
    #   - 1337:1337
    # volumes:
    #   - "/app/cms/uploads:/app/uploads"
    deploy:
      mode: replicated
      # placement:
      #     constraints:
      #     - node.hostname==hubphq-hugo-dswarm-d001
      replicas: 1
      resources:
          limits:
              cpus: 1
              memory: 2G
          reservations:
              memory: 256M